apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-secrets
  namespace: nextcloud
spec:
  refreshInterval: 1m
  target:
    name: nextcloud-secrets
  data:
    - secretKey: NEXTCLOUD_ADMIN_USER
      sourceRef:
        storeRef:
          name: vault
          kind: ClusterSecretStore
      remoteRef:
        key: secret/nextcloud
        property: admin-user
    - secretKey: NEXTCLOUD_ADMIN_PASSWORD
      sourceRef:
        storeRef:
          name: vault
          kind: ClusterSecretStore
      remoteRef:
        key: secret/nextcloud
        property: admin-password
    - secretKey: POSTGRES_USER
      sourceRef:
        storeRef:
          name: vault
          kind: ClusterSecretStore
      remoteRef:
        key: secret/nextcloud
        property: db-username
    - secretKey: POSTGRES_PASSWORD
      sourceRef:
        storeRef:
          name: vault
          kind: ClusterSecretStore
      remoteRef:
        key: secret/nextcloud
        property: db-password
    - secretKey: NEXTCLOUD_OIDC_CLIENT_ID
      sourceRef:
        storeRef:
          name: vault
          kind: ClusterSecretStore
      remoteRef:
        key: secret/nextcloud
        property: oidc-client-id
    - secretKey: NEXTCLOUD_OIDC_CLIENT_SECRET
      sourceRef:
        storeRef:
          name: vault
          kind: ClusterSecretStore
      remoteRef:
        key: secret/nextcloud
        property: oidc-client-secret
