apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-blueprint-kiwix
  namespace: authentik
data:
  kiwix.yaml: |
    version: 1
    metadata:
      name: Kiwix Application
    entries:
      - model: authentik_providers_proxy.proxyprovider
        id: kiwix-provider
        state: present
        identifiers:
          name: Kiwix Provider
        attrs:
          name: Kiwix Provider
          mode: forward_single
          external_host: https://wikipedia.${TAILNET_DOMAIN}
          authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-implicit-consent]]
          invalidation_flow: !Find [authentik_flows.flow, [slug, default-provider-invalidation-flow]]

      - model: authentik_core.application
        state: present
        identifiers:
          slug: kiwix
        attrs:
          name: Kiwix
          slug: kiwix
          provider: !KeyOf kiwix-provider
