apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-blueprint-outpost
  namespace: authentik
data:
  outpost.yaml: |
    version: 1
    metadata:
      name: Embedded Outpost (all proxy providers)
    entries:
      - model: authentik_outposts.outpost
        state: present
        identifiers:
          managed: goauthentik.io/outposts/embedded
        attrs:
          name: authentik Embedded Outpost
          type: proxy
          providers:
            - !Find [authentik_providers_proxy.proxyprovider, [name, Jellyfin Provider]]
            - !Find [authentik_providers_proxy.proxyprovider, [name, Navidrome Provider]]
            - !Find [authentik_providers_proxy.proxyprovider, [name, Uptime Kuma Provider]]
            - !Find [authentik_providers_proxy.proxyprovider, [name, Sewing Assistant Provider]]
            - !Find [authentik_providers_proxy.proxyprovider, [name, Marketing Tool Provider]]
            - !Find [authentik_providers_proxy.proxyprovider, [name, Kiwix Provider]]
          config:
            authentik_host: http://authentik.${TAILNET_DOMAIN}:9000
            authentik_host_insecure: false
            cookie_domain: ${TAILNET_DOMAIN}
            log_level: info
            kubernetes_replicas: 1
            kubernetes_namespace: authentik
            kubernetes_service_type: ClusterIP
