apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-blueprint-nextcloud-env
  namespace: authentik
spec:
  refreshInterval: 1m
  target:
    name: authentik-blueprint-nextcloud-env
  data:
    - secretKey: NEXTCLOUD_OIDC_CLIENT_ID
      sourceRef:
        storeRef:
          name: vault
          kind: ClusterSecretStore
      remoteRef:
        key: secret/nextcloud
        property: oidc-client-id
    - secretKey: NEXTCLOUD_OIDC_CLIENT_SECRET
      sourceRef:
        storeRef:
          name: vault
          kind: ClusterSecretStore
      remoteRef:
        key: secret/nextcloud
        property: oidc-client-secret
