keys:
  - &arcturus age1sl4vva0g5zsk5mp9dqqwh34t7vtjd5m9dfqdpwl9ete638939q3sckw036
  - &asta age1fk5nsur35v85fk8kr62kk768zhw78lq8hwa3efy9lesf56dtz9usafq3yx
  - &amateus age1l7adltmqwfdk663nazugqr3r65qknfc3q7jja6y2zv0mnekmg3hq2uekvy
  - &antinoos age1kufgdtz7h7r40nl6wa55zgvxfzuc5sc3mh2qzthvfvz5l778hvjq6gxdjt
  - &aperture age132hqe27z8z6t79uzsaxh6yfn2vnshvc0n0dmad53fss67tvhxcrsxuk5sa
  - &argus age1xrs7yzr5s2xsd5gqhsztan003p3z5flz88nml6js0wdwuq4gfs2qaxj2e6
  - &albireo age1jlmtpwzu3h38fe0qzgdh8ycw9g3unzt7mxg0zjtqc5r7a4zsga8s76nawj
creation_rules:
  - path_regex: secrets/.*
    key_groups:
      - age:
        - *arcturus
        - *asta
        - *amateus
        - *antinoos
        - *aperture
        - *argus
        - *albireo
  - path_regex: k8s/.*
    key_groups:
      - age:
        - *arcturus
        - *asta
        - *aperture
