{
    "$mod" = "SUPER";
    bind = [
        "$mod,Return,exec,kitty"
        "$mod,T,exec,librewolf"
        "$mod,D,exec,pkill kitty-launcher || kitty --title kitty-launcher -e ~/.local/bin/kitty-launcher"
        "$mod,N,exec,pkill kitty-control || kitty --title kitty-control -e ~/.local/bin/kitty-control"
        "$mod,E,exec,pkill yazi || kitty --title kitty-explorer -e yazi"
        "$mod SHIFT,C,exec,hyprctl reload"
        "$mod,M,exit,Hyprland"
        "$mod,Q,killactive"
        "$mod,F,fullscreen"
        "$mod,left,movefocus,l"
        "$mod,right,movefocus,r"
        "$mod,up,movefocus,u"
        "$mod,down,movefocus,d"
        "$mod SHIFT,left,movewindow,l"
        "$mod SHIFT,right,movewindow,r"
        "$mod SHIFT,up,movewindow,u"
        "$mod SHIFT,down,movewindow,d"
        "$mod,1,workspace,1"
        "$mod,2,workspace,2"
        "$mod,3,workspace,3"
        "$mod,4,workspace,4"
        "$mod,5,workspace,5"
        "$mod,6,workspace,6"
        "$mod SHIFT,1,movetoworkspace,1"
        "$mod SHIFT,2,movetoworkspace,2"
        "$mod SHIFT,3,movetoworkspace,3"
        "$mod SHIFT,4,movetoworkspace,4"
        "$mod SHIFT,5,movetoworkspace,5"
        "$mod SHIFT,6,movetoworkspace,6"
        ",XF86AudioMute,exec,wpctl set-mute @DEFAULT_SINK@ toggle"
        ",XF86AudioLowerVolume,exec,wpctl set-volume -l 1.0 @DEFAULT_SINK@ 5%-"
        ",XF86AudioRaiseVolume,exec,wpctl set-volume -l 1.0 @DEFAULT_SINK@ 5%+"
        ",XF86AudioMicMute,exec,wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"
        ",XF86MonBrightnessDown,exec,brightnessctl --device=intel_backlight set 5%-"
        ",XF86MonBrightnessUp,exec,brightnessctl  --device=intel_backlight set +5%"
        ",Print,exec,hyprshot -m output -m active"
        "SHIFT,Print,exec,hyprshot -m region"
        "CTRL,Print,exec,hyprshot -m window -m active"
    ];
}
