apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: marketing-tool
  namespace: flux-system
spec:
  image: ghcr.io/dev-stacc/marketing-tool
  interval: 1m

---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: marketing-tool
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: marketing-tool
  policy:
    alphabetical:
      order: asc
  filterTags:
    pattern: "^\\d{14}-[a-f0-9]+"

---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: marketing-tool
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcd
      messageTemplate: "chore: update marketing-tool image to {{range .Changed.Changes}}{{.NewValue}}{{end}}"
    push:
      branch: main
  update:
    path: ./k8s/apps/marketing-tool
    strategy: Setters
