apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jellyfin-oidc
  namespace: jellyfin
spec:
  refreshInterval: 1m
  target:
    name: jellyfin-oidc
  data:
    - secretKey: JELLYFIN_OIDC_CLIENT_ID
      sourceRef:
        storeRef:
          name: vault
          kind: ClusterSecretStore
      remoteRef:
        key: secret/jellyfin
        property: oidc-client-id
    - secretKey: JELLYFIN_OIDC_CLIENT_SECRET
      sourceRef:
        storeRef:
          name: vault
          kind: ClusterSecretStore
      remoteRef:
        key: secret/jellyfin
        property: oidc-client-secret
