apiVersion: ENC[AES256_GCM,data:SeU=,iv:gZLtm0fZ5EaZ9OncHiP3GfJnoiHdSdUkQMXnXzSigGA=,tag:w5Aw+qkxhJfgMW7cXo2wHw==,type:str]
kind: ENC[AES256_GCM,data:JY/49m5a,iv:sLqPOnXmKLx4epDFszE2q14WjBMZyYhmKxZgPwme1t8=,tag:xHYnDobdps9SVQ5n676Flw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:wibRnbDlGZdQSmHMVYU=,iv:kZy70Oh0dsmCVwy1vJN/lgDeJNYgPthJ7pu8y/pVOzc=,tag:XSxS8B+vI7n1mJyWVv6TIA==,type:str]
    namespace: ENC[AES256_GCM,data:FZq/POdod/0=,iv:ssWVlQzWtEdzRhtGcwPUYnUqWp+rADVZLhFiFxhzT8U=,tag:aMXV+UvzzafFbJRurVX3KA==,type:str]
type: ENC[AES256_GCM,data:egt4jS+o,iv:ObHO1NTHgtOmu8U2DPjtdRUVUMxeuwNYYAXkjDiUy1s=,tag:U2NmZKnkMqBYU+KERRhn7g==,type:str]
stringData:
    api-key: ENC[AES256_GCM,data:mGIFcRv/B4lKpacN6gJg5/OCtw7oRGyi5vOuSomGNO6kGgTIHFMpT6mrgw==,iv:nZjVZsQOjNfkuEaMuGrKaB3ar1H18YQi/mA/ODl53to=,tag:2bFLXKn9aWAhfwIau9v+zQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLZkJnWEpoWldZNHg5V3I5
            Mk95c1BOemgvTkRVQVBwWkg3SWpQLzA3a1V3CkNZRGhFNkJ2WUllN2YxOTdqUEJk
            TXE5SEd0ZmYzZEx6ejhGcy9hbTd2VVkKLS0tIFRhaS9LZzMvREptQWozRlZFTE85
            U1U2N2t5WWd6RVlPZForb0J0Uk15K1EKUys/67QLHtWoLgVIyCueQXZ4Pk+G1sZN
            frJmMiIH/I6Y0iPwcjhE/5/swEi/4G8GE0DqxmRYdeheNZRUa0VCeA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sl4vva0g5zsk5mp9dqqwh34t7vtjd5m9dfqdpwl9ete638939q3sckw036
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBT2Y1aEtVWFRzSE5IK0VD
            Z2VweUY2K3lnRG80Rk1XR1V5cUN3YUJzUmpBCkhpU2s1ZDFNT1pTS1dJclFJSTZO
            OVRxUG90YkZlRlkzSTFUYTlaNFVYMmsKLS0tIDBvZUIxNGhXaXZHYXlLbHBXSWFJ
            ZzJsVkJhUXF3cWk1amhabXdGaDErd2MK25PtlcypoSojDSF7tV4Vbx6VGRcRZLTV
            3JQ9kIPPMG1IxNpK6ohj16AonqsBo7LzMyb6AScVHQi3uTCawcg1nw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fk5nsur35v85fk8kr62kk768zhw78lq8hwa3efy9lesf56dtz9usafq3yx
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGZkx4T0NFRWlVWHlMUk9t
            ZnJkd0krSE5NUk9OdXJEQTB0ZkozbHpnYlJvCjVGOXpKWGpRclIycWpkTXYrNkFP
            ZzYwNFpLZ2RBTDhCQlZGSjc1WkxJSXMKLS0tIElwMlJZckxHc3c2aFBxQjlYbElH
            TGFmaVZQL21zSWNQL2dZYUR1OS9WaW8K5PtJ4hIiZvqcioloQo0jsvkFp8qsfaSi
            hTupUoBnDO9A3C0AofJehCI7UH2nag2QCS3Q1HyyZPqqw0A2yF5+vg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age132hqe27z8z6t79uzsaxh6yfn2vnshvc0n0dmad53fss67tvhxcrsxuk5sa
    lastmodified: "2026-06-02T23:38:53Z"
    mac: ENC[AES256_GCM,data:PNWdblMXiCupjZ+QFsj+sCtaoTJwBCC5ZWJeXBhvg3C+TmjTH6SSrl8Pn5m1gEwiyVADwK02A+hk9Lnp2RTVz258viq27E77cqeP+pAJG+1SlWuS5ByqvIIcvoUBbQZrA8/wEYcS2DcLoOM4fBulXOw5zMcRG+jxjBixcJ2nUvA=,iv:zyEwVpVXM6RYbjaPZvfbk32+eRAxX7jECOQTmYOlqZQ=,tag:PRPKNXTdrYIkb7Y0WsJWqA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
