apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: crowdsec-secret
  namespace: crowdsec
spec:
  refreshInterval: 1m
  target:
    name: crowdsec-secret
  data:
    - secretKey: enrollment-key
      sourceRef:
        storeRef:
          name: vault
          kind: ClusterSecretStore
      remoteRef:
        key: secret/crowdsec
        property: enrollment-key
    # must match secrets.yaml crowdsec-firewall-bouncer-api-key
    - secretKey: albireo-firewall-bouncer-key
      sourceRef:
        storeRef:
          name: vault
          kind: ClusterSecretStore
      remoteRef:
        key: secret/crowdsec
        property: albireo-firewall-bouncer-key
