apiVersion: v1
kind: Service
metadata:
  name: crowdsec-tailscale
  namespace: crowdsec
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "crowdsec"
spec:
  selector:
    k8s-app: crowdsec
    type: lapi
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
  loadBalancerClass: tailscale
