apiVersion: ENC[AES256_GCM,data:5+8=,iv:QOp6MRWfJuhM4Vsx9TrOpwqcx0A9+WRHBsk7detoF24=,tag:WA0QmEpAZ9xIH/wgRG/Onw==,type:str]
kind: ENC[AES256_GCM,data:kjkmAij/,iv:Q5XudCz+F6YUz8rPE6GHdym6H5yiwE6ewDODPa0HIPE=,tag:cB4xD9kCdbGQPL40b56+Qg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:TUfspSzFSW8ltzYKQRENMyw=,iv:VFEcRaUV0J+ggJZj1GcQz8X5V8eoA4Nb5kj+d1QQLd8=,tag:OT76XbY5Hqze3bAyRnkVQw==,type:str]
    namespace: ENC[AES256_GCM,data:hTg3qwU=,iv:+0856MZxccsFaBB8IuadV0XVIBXQ1WGBtSlI6HMw0D4=,tag:1HOQEHX1TaZWuEL3sLWxzw==,type:str]
type: ENC[AES256_GCM,data:ksrwHnn5,iv:Qk1kK8qPx5r4LP1OpDtlWa7a0HPePcq1lLXJNuhkIxg=,tag:w8z32N3tfY55yY6jGuoiXQ==,type:str]
stringData:
    key1: ENC[AES256_GCM,data:2j1c8BHCy3lVK7Ejagshku0hjEuIyWQ88anC3LjAOzF5vnMVCqy+hhM3pKQ=,iv:GEpXp3OwObUpG6vh4VrSIZ2ZeiF/faFiPbuLndoHhJU=,tag:gDEwXC/IjyZMmRs1jSayUQ==,type:str]
    key2: ENC[AES256_GCM,data:yvf/f3gL9GYGJwLlgsWv8uZ2jqgh0nhVDvxytdDRW6e5w6emNUc/naJMbqs=,iv:sR+S8eo4PmkCM2ceHArk97CNAiL+ckqya1/LFQKlhfQ=,tag:1D1P5IYDao5IT88WVoHSYQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmY1ZlWVFtMHpJbURCSWpw
            NnljeXJ0REVtVXhaY1pUV3prOXlWSTJaKzBvClpTVmNock02ZHhkTkI4ekxlUk1u
            L1czNDVVVU8xSmtJWkZONFVKSXlaVWMKLS0tIEtIeDdJL2ZlSW1PYVBRTlZiYlZx
            OEVNT21OMUdZR0lMNVFlYms3ZEtIL2cKKn588svDMbIE7mtZG7HeAEJvYE1/o5L9
            T3PmH3tM5fwMMei2No204suIOWvrrUMKMqFNCcT4cnAs/h7SYEc8sA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sl4vva0g5zsk5mp9dqqwh34t7vtjd5m9dfqdpwl9ete638939q3sckw036
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkSWd3M1ViWkNvTzBuc3Bk
            T3hSVE96RTlMQnI3dThod2lZZjkwN0JQVjI0CkhwQkVyMXdncHpFZWpzZnRKckU2
            V1ZzRXF6b1JuUC9IdnBmZCtxL0dId0UKLS0tIHkwVlE0ZG1KT0tjTTZkYXVXbXo4
            a0hzWGIyYTRkN0tSWnBTeE9CajVUOXcKOTsM19jUC0pT3RwHCpAHgwtGfvTAGluu
            LtP1xKxKEQ24kqEvFwRtoBTFwSW3pjO/pbQPUn62tWq+5BRDAOjX4w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fk5nsur35v85fk8kr62kk768zhw78lq8hwa3efy9lesf56dtz9usafq3yx
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0Znc0d3BHNnRoVmFUZ3Rw
            SXJ0ZmlLYjFMS2UwNllnVG5LWEZCb0dXelZnCmNHSk95Z0d1K2JkWW5seUV3MFJy
            Qk5haEt1Z2ViZmNaVTMvcHIyR3R3eGMKLS0tIFVXSG0ybFNQYWd1bnZkV20zZUFL
            SWdtOWFMZFQxS1dueFN6V1ZXcFJDZzgKe6vJRLltLpYNCb1xHlQDBrj4gllGMcH4
            Md72dapnZN5/mYCLUu9gpEmxlVTveF6bYnrLe5al02IoyY38XpSlwg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age132hqe27z8z6t79uzsaxh6yfn2vnshvc0n0dmad53fss67tvhxcrsxuk5sa
    lastmodified: "2026-09-29T22:27:58Z"
    mac: ENC[AES256_GCM,data:yaGs+RLibAvhHCBZywGmnotzbjsav8Xm0R9nlkq9zKM0FXhMls2QCu2ERffPe4vuC3vv8LSZ1TpyubInSun2O6xzUU24l8PZCPEcmAyLY2i+X89VOKVx85jw912cMF4YLLkNre7g34GaZpOibZNwSStSeOCprFS0UlCElkH/kWI=,iv:gA+ZO/WsstVR784fDnjsQfJ5Lzd2z+ezPImuvyoQ6Gc=,tag:rKWXQWKdk5q4wpAllM1NKg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
