apiVersion: ENC[AES256_GCM,data:tfs=,iv:JYu+46KNOgI5upElr+xp89ddr6OJlKonXZhiPmOGykU=,tag:mZeLFzzYPNw7liAPnPxf7g==,type:str]
kind: ENC[AES256_GCM,data:y/AxdQVh,iv:NWG7+vmc7jV4Qrq/Vza5Cai4rAlvtALDy4e6pP42V94=,tag:98XOIDiSR7lew83RAlqMqQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:WAh1C/PQ8RLYjeqh43JCJGg=,iv:SDb7Btefbzj8Tx6uQnX/9NoploIXtvS+kZnG2em0RnY=,tag:ouln4mGJz4erEAiYktgjlw==,type:str]
    namespace: ENC[AES256_GCM,data:viGTdFY=,iv:Ma5qEmNK191OjpWv2mSL6H3MTPv0cNc3no/HkxcTxB0=,tag:B0E23VkxkurcvhY2SebArw==,type:str]
type: ENC[AES256_GCM,data:BTxKac/g,iv:FiCdStExWteEavn0pl5QtuFjml4e3fdzXYxtSfILYAk=,tag:xv/uguMILMnsCw1neut7aA==,type:str]
stringData:
    key1: ENC[AES256_GCM,data:NdqiO2Ide8E6LMy7mHYmNK7IrD9y28wY6axbwtJIdthEooN4u/sW+KTtfvE=,iv:bA/OStOJLk3oQPTWsDZGtJsPvoraYhIvhdMUGUjSZvM=,tag:CY2cmOe7fW+qHt13C+iI2w==,type:str]
    key2: ENC[AES256_GCM,data:Zy+YDJsWf3JLnnOWAzPe08qdQ5E4vc26/Mbn3k2az+2HDfsFx3b6HH+gTpc=,iv:VRBF9b+OTib+c+AVV7lkEINdn8H80PpP7DgWrkNsp2s=,tag:fobLCVoEoSwCXJZcDH+jTg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5TXhNSG1DTTJEbEdQblFj
            cVkyVmN2YlNISGE3UGcwZFU1NTBpbXYrUTM4Cm5Zb1l1Tmkrci9Hc3duVXFkZ2xV
            M2VSTDRIeVlZU0xncncvZC85ZzhWQWsKLS0tIDBhWFYzVVdtSzlaZGR0b0l4LzV5
            UUYxODFTTVNnK1F4aC9JeEVvalVDdFEKToak4PUEwwJ3DEe6cfTxTkoDkCrXZcfI
            IrFI8ySyCLTCCaaAwVJ4L5DeKEkoqZ/HpjJqGWjD5gTSZdxX++qVAw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sl4vva0g5zsk5mp9dqqwh34t7vtjd5m9dfqdpwl9ete638939q3sckw036
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVVnBpSFVKV2VDcEVFLytm
            TzR5NE4rbEErMFhZaFVtN2JFeUtaRC80V21FCmpxMHRwVFJBWHJKR05vRnJIWVdQ
            bXRrd2tNYXpBUS9PR3lQaDMvcFE2VTQKLS0tIHllUFc0R1lNSmJlL205aEJWT3Bv
            WGVVdnpwODJWYmpET2VvQ3JoUWxtNzgKydi+zBCbsMfY0xQNaqdh8VpFShMYInPc
            OYgnf7yQUUNJzbSb61gSOkTT+maO6CZ781Qo3eJlBPD8hm4I1qx2eg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fk5nsur35v85fk8kr62kk768zhw78lq8hwa3efy9lesf56dtz9usafq3yx
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKWUNLbnE4d1JqNVY2MEE0
            RGx3QW0xTytZMUY4Y0IySnBCQmlyYW5GM3lVCitKYU5CL1RDdXlWYm5HQ0FieVZ3
            bm5jdVJKeTFJaFczdllKTStGbHVQUzQKLS0tIDNTTnVpVGJrWHAxV0ZaMTlxQi8r
            NlBkeDBieEVhcVdDVHZ2NDAvcThNMjQKuqnHY8DD0hZ91MiB3vIdhiqTREHrelJ0
            217DwSLR+UN/JWIbgJD87x6G0lkfFjaHOBCd9UYlfsAAFUN/3hkhpQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age132hqe27z8z6t79uzsaxh6yfn2vnshvc0n0dmad53fss67tvhxcrsxuk5sa
    lastmodified: "2026-05-10T01:52:10Z"
    mac: ENC[AES256_GCM,data:nGoB4pP1VANPfpNH8pqRE/R0iKWJbG8YvRnHr1FiM/GfvKYGcAfMoMxtXvC/OTBTYROVTZ7dq9ZtfFps9Q59+LR5P4xzZJi6XMxWGX1VvVYbB1sZIS2dbSKaJdUOfSYb9ROJFz80xB6u5BpGU8J6saSOGI9dH1sVZefbj2Wy/bg=,iv:6IoyKiValbmLEkdHpd094tr6AeJoodU8hyUQUOD4mtk=,tag:15ipTP+Xo54f5Ld3qZ4rVQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
