apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - tailscale/
  - jellyfin/
  - monitoring/
  - navidrome/
  - uptime-kuma/
  - vault/
  - external-secrets/
  - ingress-nginx/
  - sewing-assistant/
  - marketing-tool/
  - prose/
  - nfs-provisioner/
  - crowdsec/
  - kiwix/
  - nextcloud/
