apiVersion: ENC[AES256_GCM,data:QJE=,iv:28nIcWUoKx/DjL4uuSyfKpesU9tEZXGEga3ZWjqDzIc=,tag:yQmmDLkMvpUagCfOvOSyxA==,type:str]
kind: ENC[AES256_GCM,data:LsVWCA+x,iv:QP6dgeL0enMuXffwvokPek8GB6MFiBebmV9dO89Skes=,tag:4nsV9dCI765umeOj2DpShg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:VfWLpLgSxuWy9RP8uiaZSQvVA44=,iv:3M6SxlfvSn5fe8+TkGnfrK9FE03LOT7NXsa5/0le0ts=,tag:Jn/JPCmX5Ify3b5CIrnjbg==,type:str]
    namespace: ENC[AES256_GCM,data:8beuJtvUZqq9iA==,iv:2Q6DWN6pt/dLugfkjGh5OjELb3oPUDNBt6qGNPZWDBA=,tag:sz0hiTtspgBUHXYfdFihcw==,type:str]
type: ENC[AES256_GCM,data:ColZdm/u,iv:N543U2aQyMJi1cZDsdy8XpKANFfpHKTLRtpUxtbtX3o=,tag:S6sgchTDm5K2dokN9UMjpw==,type:str]
stringData:
    admin-user: ENC[AES256_GCM,data:8zug4b0=,iv:GKX3py5RrIKZ/eDHd/IXM+WvBUMnWAu6vIUIBooNeGQ=,tag:LxOgQAkuqPno04dOk7cgqw==,type:str]
    admin-password: ENC[AES256_GCM,data:0UY1KKb/dMNlw5ctlPq8+ICQ/Nm20Q==,iv:JYiRfeuiz5Ou+UNrLcgt9Y+GUuorjkKvTEJS0KdSDKs=,tag:7/jJ/LMuGjlMmkZhF3eGgA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHOUY4aEJpTTZqblZ6T0s1
            RTFyM0FjVjd1bTdqVzlhNGF6WU0wdDdSWlQ4CmpRS0RIVmRhSzgxejdwQXFxckJY
            U1k4L0dpRUU5QmIyQWcrL2ZPM0phRWsKLS0tIEVRZURxWCt6NlNodStFV2RJQ2Ir
            MDhrUmdDOHBzeHRhUlZXS3V0L2NzOEkKS+fxQOZdSZxPW3v4uG3zq1iOSEtoy5Q2
            9HXhgQE5/yu0femxR6bn2uhKTRtKLzMtX0VB4yX1+Eb0qagYYyl4EA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sl4vva0g5zsk5mp9dqqwh34t7vtjd5m9dfqdpwl9ete638939q3sckw036
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnOG5sVEFJVUY5Z3ltWkJY
            eHRYUmFmc1Uwc1pPeFNUMnpTOFYvYmtGVG5RCjBoZ3g1V0JFZzU0Uzh5RW10cTdw
            WXVRNDdvZU03UWFUT2NKeXNZajhZQlkKLS0tIDUrN2pzZ2V3bHNaamhVUTFZVHQ4
            dXpjbnRXenR0ODllb0x0a1Iydm13TGsKq2Is52PCpuwr5PeWZbzWZOnzu1Qx2c6P
            pk9O1Hd4OJADppgM2PtRsvp5JYM6T2pgWPazZOvuq0j5GdjKZO13Cw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fk5nsur35v85fk8kr62kk768zhw78lq8hwa3efy9lesf56dtz9usafq3yx
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJU1dHMDBJMTN0TVBvTzdz
            TENyaE1pcm9teGkzeUlYYjdqSTgrN2VEVEdnClAyd1lnK1NtVVRPVVRHV2tYblVn
            OWxnaFBpUitjZE9SYkFSMVpNK2hxODQKLS0tIHVMMW5LaXlEbnM0UjN6YTIrLzhV
            MlliekpnU3lLQ1hsN0xGSm9sSm9Rd1kKZyIWF9Ers0KReyUHnTCqBQzePMlih+OA
            x+8RDNamRzBru7pNdU9x2nNu8NYx5QedVZYYd4JcmbhlY9Cqk6dfPA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age132hqe27z8z6t79uzsaxh6yfn2vnshvc0n0dmad53fss67tvhxcrsxuk5sa
    lastmodified: "2026-05-03T02:21:15Z"
    mac: ENC[AES256_GCM,data:DCSdQua7KP/TgSe/vjOgWuUrfvkCnWRybiwLMxM9TkUK9svDyQjcJdA2WopBqCsRMyHiOvdQEW49qn2QaFW3npGRfFAbNNU8DGiFURDuocF6eJwoTIh3SJdsl63rt2bKWbyVPgxonRj61bvntgbfk0TWZsQ985aGHvw4ikxy+OE=,iv:x1zzC08nvn81sI6H8XmVp/kfGtYaxUK3pFHEm+moDuY=,tag:ozLggcW85Xb21GtZo6aMNQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
