apiVersion: ENC[AES256_GCM,data:SFtWRzcfaFWYZrvtC59N0ix9r7rSDZBXuQ==,iv:73XdRWqbNN2wZvThlnYgb+BPv8Ei94xXMVxIlGLOwk8=,tag:kYIxmByffA3J+GLDK8dnQw==,type:str]
kind: ENC[AES256_GCM,data:li9+F+qOiXbu5dc=,iv:QjkNJGYXe2rc+YC8G7f5FiOFIT7mHuAfa3Sgnk8K6Nc=,tag:3606Est16aPm7HL41ZeENQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:qEcKujBLG/dIv0SWT3y/bNVfbXTQ,iv:LnsX0sCXZG4wobUB2frr9qoURfaWujWuoG/n1ogULvk=,tag:UL6DI5966PsLWsJCQN4S1A==,type:str]
    namespace: ENC[AES256_GCM,data:XH6W7UzJcDR7SA==,iv:S08JHyRAPU7I1kBFdwkjuGev6AxDf7J3YFWFfjDjH6E=,tag:R0FEtv2HJVCJmjBtbDnMCQ==,type:str]
spec:
    interval: ENC[AES256_GCM,data:sFO3,iv:x9a5KIQLBM6ZMeXKoZkt2pBD6v0shkhFRo+9iKE/W9A=,tag:zi+oAt+IaPV79vNw2GHTog==,type:str]
    chart:
        spec:
            chart: ENC[AES256_GCM,data:idcDPwREYtzPOiXDXyxItQ5CIes0,iv:1Y5LsjSa8Y90j2M4T286yuIUyZ/rVx2AdmtleWnDCA4=,tag:7TGD2Gv8g2WEwHy+iDg4kg==,type:str]
            version: ENC[AES256_GCM,data:xrjnCsyunK0=,iv:2HDXQsh5zDx7er3MtTp9GtnOu9FN68LNBxpVJZNNB2k=,tag:78yM1VDFF2l8pAyWYyukcQ==,type:str]
            sourceRef:
                kind: ENC[AES256_GCM,data:qS93YOCqlI134sjMm0Q=,iv:BOxtEi/eMbaOBrOqklDZgCE9R/MxphTm75mSmkQ4d/U=,tag:k6eZwf2YkDcEPe2rPUE7aQ==,type:str]
                name: ENC[AES256_GCM,data:+7McgcuT64ITLeZd0ox0pAHt4f4=,iv:b8DDUe6AiTYwlSuttIejJRJPZuXm/pX7p+gf0RUk0VE=,tag:wHZ+AJ947d0CcYfh3xUh5Q==,type:str]
                namespace: ENC[AES256_GCM,data:4Ecb9P3qL/qD16s=,iv:VqdrI7OgymJ82AKHC1wwaFFYR0X9CPXkShcLihm3SOg=,tag:qYjSQIP3As7WYA7m4o1EIQ==,type:str]
    values:
        grafana:
            enabled: ENC[AES256_GCM,data:e5/a3g==,iv:+GKRaJthiTedZp/GWhPnS6TaCaTg9TDsHKWKh/7FQzI=,tag:qqKvydbSABogyh2AL6i2Gw==,type:bool]
            admin:
                existingSecret: ENC[AES256_GCM,data:b8VIZuXA+jeArQ2GQV9hOC22Vcw=,iv:uMdxyw1NIsRePiDjWunq+tpHGco9XRrfao7hmOlBKqc=,tag:cCHxX2nyNOHKgznPdqnr/Q==,type:str]
                userKey: ENC[AES256_GCM,data:/de3559hiwARXA==,iv:HnEzWHl2qylQyDMDVt3S0bD4H61cDE3Gi87+eaO3irQ=,tag:tfZKnhUELA5JBen8QQtVuQ==,type:str]
                passwordKey: ENC[AES256_GCM,data:5gWAmpK3EcxMnoMfkTE=,iv:rR0knFQDbs4y+p23B8iiUL/SxQjnbQpMXgDOY7tkX5E=,tag:VFbz/inoVPmciRMGY5K3cg==,type:str]
            env:
                GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:fPMFeHksUfLuJbK6jsSWQglJ8xcpRyXP+VAG5itGfR8APFalptvAGA==,iv:BEyfJoujjhj4R4aLKsmm7DPg+XMAcchRvrb4IW+o1J0=,tag:riBAfxcoN/A3nmx9RpzArw==,type:str]
                GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:DqitE8d+VHsfbVCda/tdSLIV0TYqVtRo1HDNqTeQC+IpxKTfaQ9W7/EC4tNeTkZPjXB+pEJQpDP0VX7ske6BeOqYSSHys5yttGHe08FqOv4XU/haFQnxY+QQTIh+h/bLDyj7n82BKSjEHkjsPz4yOvi1+w2/U2bYvRDuiJBkhx0=,iv:cUF9/PeXfd3rM2iIFXb/ucCJUplwlncoJ02x5fcwTaw=,tag:sraF2Jh2dmwQz+8w8wyJGQ==,type:str]
            grafana.ini:
                server:
                    root_url: ENC[AES256_GCM,data:uWlC5POQ6xFbP4TBWonHqXvcUIWnROjmaWcbf9castg=,iv:sAqNQK9RrpQRiB/M1Dy/MBTnq8t23wwtB9kxg1fbArw=,tag:GyBME2Ovu6TPjKJOfvdF6A==,type:str]
                auth.generic_oauth:
                    enabled: ENC[AES256_GCM,data:bBDjQQ==,iv:Ii2w9gmCF5FFuWREvPFQs88zABteKqfA1vxMQ7tgQHQ=,tag:yqvdwphJmFO3I9LbTdDYxA==,type:bool]
                    name: ENC[AES256_GCM,data:rD73HvEuNeMX,iv:M7bqlxSgTy/uX14B9F2pDYjSf7zEaMKJnoxAMVELQyk=,tag:bT3nXoAszV7lYFaE16J4KQ==,type:str]
                    allow_sign_up: ENC[AES256_GCM,data:K3IQkg==,iv:Qejk3qngYAKh3faeYpFuSRw3KjvgQE6z+jhwX2LwsrQ=,tag:F+XvsmvoZIcJkwAtnVp5+Q==,type:bool]
                    client_id: ENC[AES256_GCM,data:ulTZ57KdX/3Ed3g4SBu+/scGhbxOZ8L3UO6l4/vQf7/k5GrsKUiB,iv:6TxWtmMXWbEdB7e6AhX06T2lvz6v26hWcJOUllMkGZs=,tag:Zqd3yFz5oUlfkHv1rm7BIQ==,type:str]
                    client_secret: ENC[AES256_GCM,data:iUDGT9rtjFduWa+1EGLqZEI1SwIzFcoP6sE9kA0m/P8argEG7gqRv/Mwwg==,iv:dJwholLpdSQg1w1UWtMA+HIVkoT2uOSFHx/BeD8tVvk=,tag:2OeYP5SMtSai+DSVqGFUUA==,type:str]
                    scopes: ENC[AES256_GCM,data:4nVZqMNQerB5ZB8rH3G/xpo5R9o=,iv:osjX94wFfcQSVzVe2YZJrPh74Gjtyd/UyIeigLTU0v4=,tag:bCGVOQUfIFN0BQLbk3ba3g==,type:str]
                    auth_url: ENC[AES256_GCM,data:XPeGS0lpYXHsqrgwT795GewFu8lE1+iGCatJGr8PquIRTo/nz+h97yh9HuLGImP/Kz+wTwxwucd9yPnt8rCZ/g==,iv:QeeS+FMuzItILGS/KwPnA+45jfEUKlAZ0h/Z7qtqSB8=,tag:8axbV7DESwQpmVIdBjbElw==,type:str]
                    token_url: ENC[AES256_GCM,data:vlEiiHzTKoeIDv26kgss5+kNCxHojxYLQ6o+5IhDNL17VQjNsfv+l0RJEzSdMF4oL+RvN7KDJDXycFSD,iv:ni1BfipcYOdwnpDFndtLjR2jJBJh3R4aHqFa/mCPF20=,tag:uTlwvNHZooBxznULI6Gw0w==,type:str]
                    api_url: ENC[AES256_GCM,data:WRxu8FxeSb4g0U4bvNbPbbt5ktGAcK+npCs70UN19ACwcZMFff39K8SsX2gbSjpnqle6h/R1uvG9fYjU5oRE,iv:lP2GRx26v+Jvr9J2LKsAv1w69fHO7EssK8jvIdZJksQ=,tag:fSVrAZZsH4bDqCaajDxjZA==,type:str]
                    role_attribute_path: ENC[AES256_GCM,data:nFhw6lHSfkDQseGUlhUQ3L0SKJPEr46h9ziALmkOVH/hc7xWnGAAFJxsM3TwAxxD0BXBCblSv1wectg=,iv:u2MBtD2u1wcNkm2E9oQ7HdyKzTUv6KnGVgdDaF5lvso=,tag:mIxN+fCzvZbKemGG9WFbTg==,type:str]
            additionalDataSources:
                - name: ENC[AES256_GCM,data:eBABNw==,iv:GQFkJliLqwfojFQAc29mve1esEmKC4NjuefIAWWQLio=,tag:K6IwaLc942BtDXzUqABaDA==,type:str]
                  type: ENC[AES256_GCM,data:lR/G5w==,iv:Gaw3OAdkgLtIgbZwEIDiv7Wstf6yxriQWpSNt5P26So=,tag:yBZR4DNV9GArVeIh0Kx/Dw==,type:str]
                  url: ENC[AES256_GCM,data:izF5jw9whmGCJRas1rlKR1rP1Rl2VLmyZ0VJtG41rIH4xOcWuxS1cETh3i2L,iv:ZdUm4qp73vH0eSOvBtbB1PflsSoUGOorxJ7fAwzIGqY=,tag:ruLjQRKEySdnpGIiS9iyLg==,type:str]
                  access: ENC[AES256_GCM,data:XoUNU4Y=,iv:/ZBg90DAy63fEJ0j6J1av736cVk6Kynbc10Eg40vqag=,tag:ZrBNJ5udkJm35VqGmAPwJg==,type:str]
                  isDefault: ENC[AES256_GCM,data:10z4J+I=,iv:8q/qGnMGtNG9psIVR+Ucd+fzldW3YdpZ+wHt1bJn3VU=,tag:crecaP/aM02lfn/aZ0W7kA==,type:bool]
                - name: ENC[AES256_GCM,data:3WIhMK4=,iv:zSI6/at6SeQucjsJGtT2/SQOhcRE8ZRU7pTOfH71LBk=,tag:4udt/QNkXe+9yh0s9RUEAA==,type:str]
                  type: ENC[AES256_GCM,data:W9meTPw=,iv:cELOQZg25w/zzqVJnL+bVXb5X8EvgKVgaopTJiqc/Bo=,tag:tsnf7kwNLxW2X2++8LsQvw==,type:str]
                  url: ENC[AES256_GCM,data:JmNoTN3/qRBF2fE31bAvZwWLcabTFECIp0W4atouJOMPFCrjDFMhbwVZDN0RPQ==,iv:7LKLqwf31KiT/et9vPTjZSZLV/xetTzs/UwkuPFj58A=,tag:DClIpYnEzQ7xdYGU4mOliQ==,type:str]
                  access: ENC[AES256_GCM,data:7Tysspw=,iv:cYh6vBs+6nUIRNw9S+rajLsPu2Dnt6KoWupZblozJ1Y=,tag:73a3S2m3gE/v79SdkBm/Ig==,type:str]
                  isDefault: ENC[AES256_GCM,data:NjGH314=,iv:7BX/GCA4m/N1ZnrIWsNnnlII3ggAjvYAvMT7DXeure0=,tag:cbinwFzdxpQnAub7t/fneA==,type:bool]
                  jsonData:
                    tracesToLogsV2:
                        datasourceUid: ENC[AES256_GCM,data:Rzj9Hg==,iv:r/yaEk/XaPPwi8KqzmPFhqX0yTxrdOj8tboEk96u+/0=,tag:ma89Q7aZcJCP0pSOcETQAA==,type:str]
                    lokiSearch:
                        datasourceUid: ENC[AES256_GCM,data:VGxZBw==,iv:r+PjSh4jG6LQxQ7nXUNQddelq+P9Q7/YLRrk7tWqedc=,tag:Ajrh9K2/ecZa9YH03bEwKA==,type:str]
        prometheus:
            prometheusSpec:
                retention: ENC[AES256_GCM,data:Wclw,iv:y0b8QuKSJeaz5A6xLqcbBu9rONloGiFHuji0ElzKkWs=,tag:V8Nb0/wVeBTzVyio5bSZXA==,type:str]
                storageSpec:
                    volumeClaimTemplate:
                        spec:
                            storageClassName: ENC[AES256_GCM,data:LOS60kaiItmQIQ==,iv:9hYUEmu0E1okM5+Vsw2Bf/Rpc5/Zp9R0K8lvi4MGU+g=,tag:ATanBx1V/SWWd8pfDUB98w==,type:str]
                            accessModes:
                                - ENC[AES256_GCM,data:OATQ2z4PYyxqsL7QjA==,iv:F/zd6czn2Y82+04TbAVU3/jKYvBCmDnnm+H9hUousME=,tag:tUHCDNZ6w4khAXTyA1UQ2w==,type:str]
                            resources:
                                requests:
                                    storage: ENC[AES256_GCM,data:kPQhhA==,iv:JQrEvXEjRWfzPlQIGERaHcW8jBaGmF/bqWH5PnuIovY=,tag:1J3dkM0uNVMpc3mkjXIGww==,type:str]
        alertmanager:
            alertmanagerSpec:
                storage:
                    volumeClaimTemplate:
                        spec:
                            storageClassName: ENC[AES256_GCM,data:HuNDdWD4EPkDqA==,iv:AKQlJz/8GHOj3XIqvCplaG8y5SmyeZbk1VU774310+w=,tag:rTi439XuQuXpFG0rrqfMjw==,type:str]
                            accessModes:
                                - ENC[AES256_GCM,data:eXTzXSVXE7r8ePqjzw==,iv:9207fUEnddCZo6RpfwBWN0RIOGwnTLPvF5ceWh7ASXE=,tag:fPZPS+2Xr56K5MIa5EFg7Q==,type:str]
                            resources:
                                requests:
                                    storage: ENC[AES256_GCM,data:Wy/q,iv:V5HrJMYFJ52EZj5TzJZtCVLChllGv9ECQcTzFxRYhcM=,tag:dkgc80tKFsrlzkQ7ifaSRg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKVnRZZENDOUhOU1NZRXly
            blVzODFIRzJsTHh2cml5NERZditqTU5QUnprCnI2R0t3RStvL3FNVnZka1RFNVM1
            Ykp5N3Bxa1hiSHIxOC9xK1dlL0QrdzQKLS0tIDFpVnQyYzd6VWIyNGZ4eTc4eVcy
            clk2L1IwZ2xEZnVFUkYxK1NxYU54S2MKZuXCVSG63xtHZ3gLcuurKg4FN0BmGgRN
            8xEgC/z5hnsTE4x8sjsBQ1VzIZR++kSR479j3icecj8jdAYtdYI7mg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sl4vva0g5zsk5mp9dqqwh34t7vtjd5m9dfqdpwl9ete638939q3sckw036
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlYTJxTmM3WjhWRzY4OVB0
            VWJ1bzR0VUtMblQvNmZKS3p3bjZLZUJRc0JzCjY0WThrdkFpWkFlekVIaFlibFlG
            LzFqREo1OFUvcjJLcVUrSDJPbndPbTAKLS0tIGE0Q2kxOTh1LzcxaEljdUJSRG44
            VXBYV0l2aHRVTSsxZFAxZjJ2MC83cTAKzMRh/4vtXuijM3kaJf764t3XD3sMOfUi
            +jNWMwf1JtH0U4/vdt2ehmuQWBMGwZyCM3iTQSPflogTuqRc8PUknQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fk5nsur35v85fk8kr62kk768zhw78lq8hwa3efy9lesf56dtz9usafq3yx
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFSjJiZDlMdWZsK1U5Rmhr
            bmNidGNGZ0hONkJ3UHRvUmV0NjVVSmM2a2cwCk5TamVxNG4wdlFxUnVWWjNsZTJ1
            Mm1WZnozOEd1cU5UMWtKV09qY2lVMVUKLS0tIDcrcVNOYjNKVGpSQ0x3ZVAxUTZW
            M0tzMUdDejVpMy92dTYrSVBYSUNXd2cKqSbwjvz3bjTlkDb3yeiObzcbHe29OmYS
            HBCV2K9iTbV2TpaYPavhkLmSmCEsRZdD/tJWj82mc2rU0vYXfdqkaw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age132hqe27z8z6t79uzsaxh6yfn2vnshvc0n0dmad53fss67tvhxcrsxuk5sa
    lastmodified: "2026-05-10T03:34:29Z"
    mac: ENC[AES256_GCM,data:ZQcocy4u1hKJBvQzWL7gxlI5plokzGHItLlyl6NuX9Gzy8TlnE+eW0tKJupXG/790WVk8XxR7hq96bNa8AI8UG2EYvaHTD8UthHux5l3M+zBPclBKoen9GggPZuFhe9oNDdxwCuZ1KJpHrFOgBPg5hOBhhmd2+AG/qBTd7ix8RY=,iv:qHBKr5ZHmzNNNpoXIfSD0iyGHDIk84LOHkfpN2APogc=,tag:1vm2Isj1k5qfE1tw4TU8nA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
