apiVersion: ENC[AES256_GCM,data:88senZzPm/CEQ7h3dY3pmWiyiZWtsli/1g==,iv:AHwOPjo4slFG9voMYFh54ZWLQJy6xV7p7V1qMeAxxgY=,tag:dLeJfKh3bbvXD9gqoZBJ/w==,type:str]
kind: ENC[AES256_GCM,data:H+2L8eHmM/bSosQ=,iv:s0cUrhu+wINgV2J3+hHPWi8SN4VfnKHeUfY5sFUH+Dc=,tag:EwVen3NUBYNWC8j5zawRtA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:imASvc5qeOP04zwrD3mabNgYV6Kc,iv:XgDRvctR/GjlartUdI310XYZMp0E0IyJ8Y89qzgRoGc=,tag:DHJ6XxdtleDgSJzEX9mT6g==,type:str]
    namespace: ENC[AES256_GCM,data:SqKr9znneiZmhA==,iv:u42VrapjByuJAxBnxm3MY7PowCXCeummB4Mxe+SKNNA=,tag:ps2TnFFdJk2mOerTUmHUhw==,type:str]
spec:
    interval: ENC[AES256_GCM,data:Qk13,iv:x8Y7IajydCjE2dB1olAsUGBV+94Jtx9+vhl8d35xTnI=,tag:z5sdiFd4Nlz/ZhDj5Fsdpw==,type:str]
    chart:
        spec:
            chart: ENC[AES256_GCM,data:ErlfnolmgkwoMNgi5kgHwW3KcleL,iv:+yTcUfA6OL94prnI+OohiTBt0XJQOr4/gIfgn5ekcvY=,tag:20u8sepW6cgdmliK1AbQdA==,type:str]
            version: ENC[AES256_GCM,data:eYM0nbdDaOk=,iv:x4lv7cw58JmqQVNDsRzBMJ6xk1tNNjkW2KkuC2s0FTo=,tag:X6MFwUyFUdVNxMeonteQCA==,type:str]
            sourceRef:
                kind: ENC[AES256_GCM,data:HYo9O4yx6R1OmiBzsYA=,iv:jFdD3tTZ688D3bfklhmG/AIqPJIDd0PTZ4RCKRuWLDI=,tag:EBGCcatWyJ14QlDROsuuAA==,type:str]
                name: ENC[AES256_GCM,data:DCRzb+uVwTO4dzuJeDZ+UcEFIRw=,iv:9j9OY3GrX0PTXDdezhAji+vmqlb10JonkiYA0S+k8O0=,tag:6giHtCPYEVEYlbkDplghmw==,type:str]
                namespace: ENC[AES256_GCM,data:2uEaTo29a42xOjk=,iv:6FN9DvgeyyZRvkQCg2AlX22K9tRg6gk/M1QeWpMlGwE=,tag:SZmiQeN6mnqMdIe+h5Wwqg==,type:str]
    values:
        grafana:
            enabled: ENC[AES256_GCM,data:1nNfqA==,iv:DHCruXtvgPqX5/kDjLzGX+MdEKoEgBgK/2TMB66wpxU=,tag:eZUmYDUvhGTAlbkUl2jZtA==,type:bool]
            admin:
                existingSecret: ENC[AES256_GCM,data:i3L5k2Rep6dg9Cln9wIMJcQPzHU=,iv:OQvZUlgemH5547euqZzHj5qir2r7+Z8WQGLArIHO7Mc=,tag:2cQnc64Dm/WyD4811C6JLg==,type:str]
                userKey: ENC[AES256_GCM,data:Akdwgq3BY4X7BA==,iv:2+RN7KbUuSLrP+JII0DC5OfDbh/TtossPzVapZeR5Cc=,tag:ElxgXpnWQ5YWxAqnjPDiMQ==,type:str]
                passwordKey: ENC[AES256_GCM,data:rdqh5DQNkjReOuPQBMo=,iv:UnIMz721FweIgSGnOwGTV2yn9WFP5dFNl9KUrdu8dBM=,tag:+RIkpgFMf5og8IoDa2kE5A==,type:str]
            env:
                GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:fAf0YsCG7rySa9B9BptSEYEDC1bEpMk3JmGYhrCQjR5WiUCSLQMuhg==,iv:YAEAv/lyAd90hsbSHv5XztrgiUdUxp2yBbEH8JpVShY=,tag:2sF0oPulO5L0ZP7n0MaSog==,type:str]
                GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:25DQv/p3HhigKUijakMgFiKBdHEvG8nPUGwVc86V1udRafyPNZF3jK0AMNTLcgP/C1pYUmMAnMDN7pU5ItsPRIZYYsJP0HQjxTqI7Jm+yTVaV2ij9sAVEMoLcYUHpFLok1Mq2+FajcvME9H+UPGu1grfrTVGvs/yqQR6URzHQzQ=,iv:3k4oWgEXckGPxLorAXiA+oE4F8RK3/1N9NR9tBSD5aU=,tag:LzRGaYE252uNSepntn+UWQ==,type:str]
            grafana.ini:
                server:
                    root_url: ENC[AES256_GCM,data:HVQZBMrZVd5bfQwx018MgETaaNKDcf2G70HLWmqy55tg,iv:1W6lF0EWV24R4GePFc7QMerljVSnwXQqBJc1SqzYrtY=,tag:I6BJn8SJfXtqHOo7ICWOVg==,type:str]
                auth.generic_oauth:
                    enabled: ENC[AES256_GCM,data:HcOnpQ==,iv:h2vr/wrtGwdig4HElG48SmbOkvhaQTC6L3bd6wEmSAU=,tag:LKO9gYYFXAkSMegjMY4gyg==,type:bool]
                    name: ENC[AES256_GCM,data:xwZ+RD9oj+QR,iv:8gNfBpJQvPcNQUuHJfenVG3BLBPlZkeLtljYLV7oxSU=,tag:pDhd9X6mxU556rsoR9T8NA==,type:str]
                    allow_sign_up: ENC[AES256_GCM,data:axqsbw==,iv:UQWgVYDk8pi14gJoUSXHUKDblAnCLZoCwUdAUU131RE=,tag:uXgk7YReXaT9j3XyAKQoCQ==,type:bool]
                    client_id: ENC[AES256_GCM,data:NIrhPc9iCbisPHK5xzL4SQLIv3UJ5J1vfqWDHMaO/fGk5JO216nT,iv:Kub3BLSgY0gJmMeWbx4PEDyE6RVc5a12jvFptFuD73M=,tag:0xiZ347rAd1tnQ55HDwxzA==,type:str]
                    client_secret: ENC[AES256_GCM,data:nreNsVEWfIOXaJdKjrgquWxVZCN24IMQOrizfHNofZhQI9/KC6KYDUAboQ==,iv:a1yhLUARifVw0ZjMzo/bHRfeRCNjBeZ+GJl+J0gYvxY=,tag:XyHJQGB6oIuPMgHJg7yK8w==,type:str]
                    scopes: ENC[AES256_GCM,data:iwf9TP8ptahasVST+H8CPn69wPM=,iv:fCDeIPUsrtEPIfNNsVD0BptZMF+7eHHnnooYBPqNnRs=,tag:OyIaFCcR/QZ0gt3YW4NYFg==,type:str]
                    auth_url: ENC[AES256_GCM,data:KegYZPIjuT3gElntwutAJWDTv7f374xZCABPsAr6NVJuBhzrXAzaePRzZwo3BgjSiWoQpVoRtm4X2kmF,iv:jUC0a2TMRtdZ9jZK26bw6y8hIlDUN2xViNvTPcNjywY=,tag:OvegnZgtsop4z6OKri9Crg==,type:str]
                    token_url: ENC[AES256_GCM,data:WCdvlcN2h0t5vy5kpUNOFn4kGozSNtk9GvKfZdpnCDEBHmlJ+jDtmWIK0nezsf6UcbnDXwlvOSY=,iv:BktCQKeuFPL009kDm9xwa5rfIqfJFQrGSAERSjjkPLU=,tag:jY8zCvzR7Fx/aO47QBrhZQ==,type:str]
                    api_url: ENC[AES256_GCM,data:O6cjNK0+H0cewgdCb4SApPNmSc8iOpRW0f3/RcHVG04N2QkJD5UIf7Q5yMaRlXneBpt5jAjDbbdepNo=,iv:oBF+qK1zWVWpngpM4kv1GQ0xpG0i0t9e//j2a9P7aUk=,tag:l6ryuPO8fD/nacU5TfFGzw==,type:str]
                    role_attribute_path: ENC[AES256_GCM,data:DLHb5dzYxe5Gq5jDhfoYo6V+WXDJfO3jfkfx+XGuvG1kAvEsOnO/zkwAlbPI0fM+Nm7kZjk/+8xGrHE=,iv:TXMI7prMLfJsDPlyk++/PHTkZn0i0aX3cjskrU4a58M=,tag:BxhHDYHkJygZz/9UY2lqig==,type:str]
            additionalDataSources:
                - name: ENC[AES256_GCM,data:vbmojw==,iv:8gokhScg0G6Y19Gk+GqIV0jyEYX/j2q0+C+pKw0maCo=,tag:gNiIMSQVlpe8t6Jg6+K1PQ==,type:str]
                  type: ENC[AES256_GCM,data:qbPSFw==,iv:HeZhwQG3AY9kk5cPdvVmAEibrO4eg3HdigUOyJxTZrk=,tag:AKfXQ2GStrBfo4CBUhNMDg==,type:str]
                  url: ENC[AES256_GCM,data:93DTKG9VboJ2aTTreVM1nrNMjNc1YSXrfwI9kzRXAi+7YdohxpG92pvCmD4y,iv:88FVrqOxAjBXQxfg8IHF1OP+SFx389JYRbqTXh8xc5Q=,tag:BT196G6USNOed4Bho9Xq5g==,type:str]
                  access: ENC[AES256_GCM,data:D5oQiN4=,iv:5qPldNDV0D/aE3lEVxd8dRjvvJL8UsrXTwaYTVujISc=,tag:g+eI9t5WfdmYZmLIjVuncw==,type:str]
                  isDefault: ENC[AES256_GCM,data:biHywFQ=,iv:Xctw9QNJZt1E25k5/wbZmNlELZJMLuqzMo39i2CR2tI=,tag:kUY/GhBGVdQdYw6wB5mdNg==,type:bool]
                - name: ENC[AES256_GCM,data:aeUf2ko=,iv:Tdv5ATro4eeYjkzPZ2TJB7T44JqfdUh8XjaHJ+7WeIU=,tag:yx7v7H82EhSLbAA7lAikFw==,type:str]
                  type: ENC[AES256_GCM,data:wLTjjaw=,iv:ICqgyDyamW0tMtPzKr8pCKtZEvQBB2yDSptjo28Qxl0=,tag:XEbYw00M6am+Lo6wDZVb7g==,type:str]
                  url: ENC[AES256_GCM,data:ZtIgOnXBB7BdDjSqpPko8blSoyW6ruoS/oPZkrE9BuQSVa+3EAbsngaeBcKfQw==,iv:DCrag89zzRoDn7WB1E7yN9k08/iPH1IOmKBJI47oMPE=,tag:jktWL8Hq9xyshxG7BQMiiA==,type:str]
                  access: ENC[AES256_GCM,data:mJ2Srfg=,iv:gWtx2nzKitK5/N5RcnVe4ZNTGkNLMfBXIeyhGIpnuqY=,tag:TBcw/eEFJ369FeTqftMesQ==,type:str]
                  isDefault: ENC[AES256_GCM,data:EGL73wI=,iv:1+2ANg41vLxbVOkFAVvT+V5CnloY8pZ3IGl1cT4pS6Y=,tag:eVdIxKaYupjeohc+sELnuw==,type:bool]
                  jsonData:
                    tracesToLogsV2:
                        datasourceUid: ENC[AES256_GCM,data:KfYrCA==,iv:a29nYT1dhe3zAOYZtVk1WfTP5B8Oc2TA5ZgrfxK5toQ=,tag:13yNGVeCRYn0VJHnSnpgMA==,type:str]
                    lokiSearch:
                        datasourceUid: ENC[AES256_GCM,data:5NpFJA==,iv:r1TwV1T3dQTLzKb8gwkuTELpdKSqKdVZpdFKHo8OWVU=,tag:KDH7NPx6wrY9OonHfl+EVQ==,type:str]
        prometheus:
            prometheusSpec:
                retention: ENC[AES256_GCM,data:VWR1,iv:WfPyTrELf0TB5MAG7k+eg/iz5tP5pOkh92ZOk+2Yglg=,tag:AxgxMdQOnIkoosqVyBFaCw==,type:str]
                storageSpec:
                    volumeClaimTemplate:
                        spec:
                            storageClassName: ENC[AES256_GCM,data:MoHI7wzzBlcvJw==,iv:tNqYv9HHBBeop3fB2f2yP91SGWbqsqgFLvR0o2QGrKw=,tag:mha1XW/kjZStQ3BeIh5TUQ==,type:str]
                            accessModes:
                                - ENC[AES256_GCM,data:I8NA2W8utyVrX3E3CQ==,iv:t0oEfZgN0x7dpuBOSSbZVSkekDq+QYWeyRu9ci2PHbA=,tag:po0c3De3I0uwWvGJGsNgGQ==,type:str]
                            resources:
                                requests:
                                    storage: ENC[AES256_GCM,data:I6jmDQ==,iv:sdHJ+NG7yxUt4nGUIjSucCG5o5ZCpzFhrvcsVRfyQc4=,tag:0P9nfJ2/NCHcck6jEZC5HQ==,type:str]
        alertmanager:
            alertmanagerSpec:
                storage:
                    volumeClaimTemplate:
                        spec:
                            storageClassName: ENC[AES256_GCM,data:GHk+8Na0cvPr7w==,iv:R7ufD3oBbRPBmumQP1IZVrSwXTAAExyUcjlElMXaWz4=,tag:mepGC+OWVwcK41dqYTcGMw==,type:str]
                            accessModes:
                                - ENC[AES256_GCM,data:6AOf+zXB7svV6a/MEw==,iv:uOF4CtMV1v1to4jT5pOmTDN1RCOHgdKVscmP3U2vJlo=,tag:s9fSOwKNj4ICygWa/WGjUA==,type:str]
                            resources:
                                requests:
                                    storage: ENC[AES256_GCM,data:euqP,iv:m1mwEB30BeC3t68aVwkLBSjvCDNEY0CunjvqVILprOs=,tag:5JTi5yssg4jALSRZ3M02Iw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaSXozWEpkbkxxTC9DcmNn
            TzYwRjJSRllGOHIzNmdBLzYxcFY3cW92ZGtRCnp5Y2lUczl3SDF2eXpjcjJGOFpp
            WU96SGEyVm56cW94ZGJUZEt1TFJJV1EKLS0tIEdmajA0dnp6YmovU1AyazlCR29p
            eXIwaC9zeWU1UitGNHJJbXNkR1hxOW8KtoxJvQ81F1ECPZ47U20MSkN/GoTR9bsh
            JwJ8PIZ1hBtr53UOLIDXqkJefVlC3s37F25u1VyWtPyRrLEoItjPeA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sl4vva0g5zsk5mp9dqqwh34t7vtjd5m9dfqdpwl9ete638939q3sckw036
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZHFCZEwvdlVtZFgzM2lX
            eENiSjhUZFcrS1FvVnFCZmk2clh0VmFSb2lZCnV0UEt6Z1F6ME1lSzRQWjZ4VkRF
            cW9ZeDJ1d2R3V1plWVI0WFh5Z2NxcGcKLS0tIFV2ZUJBTkZTSURNZXVhMk1FQ2tj
            cVlIUkc5YlQyOHBoMkM0MmRFbC9ZM1UKQ0a+WyXpsO9nYoA8Z+smEWqVte3VIjSg
            tbmxCqF9BzBhvPQg9i9k2X8G+zjMS3l3AVTQH89UkrTFpigkrJFfnA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fk5nsur35v85fk8kr62kk768zhw78lq8hwa3efy9lesf56dtz9usafq3yx
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCdHBicmNxKytZMGtVeXIr
            M0ZSQU5hUUltZE9wY2pEWGZYbjJPUFNNTlRjCmsrVUdMTk1mRy9vckJWaC9CS0FJ
            c2pGbUdyQkpyU0ZGVlFaTDd3QzVmRlUKLS0tIFczbEdONWRzK3RwT1VSNGhZdjFj
            ZkhFQUlTRlRHOGJOMjlQU2RyYUplSlkKbqlaedu8OQJHl+cYPemzIl53chF+xdhE
            bp90yygV0KZl0eKCpcl6Tifdd0sAbDGPvlc3Qc94qYx9mhsYjlTtfg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age132hqe27z8z6t79uzsaxh6yfn2vnshvc0n0dmad53fss67tvhxcrsxuk5sa
    lastmodified: "2026-10-06T15:28:41Z"
    mac: ENC[AES256_GCM,data:vBs014I06nq1y5RwYnJmdMCPzYz4E5qW3sgOiVUdBHlIs/j/6gnJXYbTpxZxxbp8f+RSkm4s1wVbv0+Iux1tQ0qDz3vrH1+iyAfer1szCToNFvrsLG0VGv4+LLs3x7elJOqjs9+SIMj/vME7p2/BAp9QK+P6EbpXsU3poOBdKv8=,iv:+zaQ3+VhSYTRiPRa8pfCDdrjxEiYvajVZrRErZSzS3s=,tag:TsM3baAYAy63e1YN2p2Z3w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
