apiVersion: ENC[AES256_GCM,data:t5pr2l7lGzk7xWzO7MwV6P22LDBdOvXMFQ==,iv:JXC525yFBhBzJNOVAiSWOb7K8c2Wqr72mQ/oSrwzd8E=,tag:eUam5OhkC8V0Rq455WrEPg==,type:str]
kind: ENC[AES256_GCM,data:O5ogPOaJsxbGn1s=,iv:ig59eWP5JqHaGFtNSHt6vzrNDYmqSx6rgGtfaWpx6xo=,tag:GhGTuPCR7hQ3//Y43IB2gQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:fJIIbWPgkyHYtVW0/uw9icQDQQIo,iv:C1FASw6C0iPi+Y9/m/Zhiy3ZZkuiCMn0o+KiGNL9Yag=,tag:QsfGFhHFb2EbwF78B56VtQ==,type:str]
    namespace: ENC[AES256_GCM,data:1YDcRr3tHq+8Kg==,iv:7Vp2XYQXJCUhLsSiStL5Jhuhk6gRd0uJaMgjx1sOpLU=,tag:t4LwUPh3ETM4Exj2qjBTlA==,type:str]
spec:
    interval: ENC[AES256_GCM,data:FI8v,iv:2dRrxZ3NJiWYqcg+iccg+oTSxwazie/b101u2RDLnXQ=,tag:ccL1wpJmytsO1TR265Qf3A==,type:str]
    chart:
        spec:
            chart: ENC[AES256_GCM,data:OccOrjiNIQllXvU2vAn4RrnMI3Zu,iv:xUw5xqGpXqU9A82pCC2rEplawLsvkA1tbgSenLYcMYY=,tag:5Au3nWRqBFKmVNL2MsxXeA==,type:str]
            version: ENC[AES256_GCM,data:5GF4rWWh/hk=,iv:Z3JBCqnKmo8AlTY9xCz18BW5TqcC9Cwq30MffrAPoSg=,tag:UKovrNi8exUvcjJMbc9rqA==,type:str]
            sourceRef:
                kind: ENC[AES256_GCM,data:F6Jh/KhMwapXwNtaKF4=,iv:BRmZW2mMe4KkJoBQ2FVMw8ouZ1MxR7Pxx4m1kVgue1s=,tag:u5bZHdscArYTE1hr/VaO2w==,type:str]
                name: ENC[AES256_GCM,data:etmeZ5BlDDW6cAZtS7DEgLOu508=,iv:5wsUjujgAuuchQhG+Beh6pUws/P/RtsKrcVHYAoeRW0=,tag:paeieSbEZ/uEc15vQczLdg==,type:str]
                namespace: ENC[AES256_GCM,data:hhLGdqORAZit3Bo=,iv:9FC3sEOk8T2hMcMDNhW8AbUfJzO34FyOnZLUxu2597Y=,tag:GojA/sOYR3TqZMcIqZotBQ==,type:str]
    values:
        grafana:
            enabled: ENC[AES256_GCM,data:4lt1pw==,iv:cShQwbI6tiCMsiMkl2cSylKlja0h+DYkiU6Mlxf580M=,tag:LzovFLzhFs4HX2vRyv3CnA==,type:bool]
            admin:
                existingSecret: ENC[AES256_GCM,data:jw7UjTgOt5wygD9xQB+xhtYgRLo=,iv:OUbXC1JJINHgB3eSumiojUZr3gWB6UBo/Il7JXNZ/Ac=,tag:2xyf1w3G1J+k/ZaGky6Y2Q==,type:str]
                userKey: ENC[AES256_GCM,data:Q5FZ4cK/th8+iw==,iv:of8Np9Uc97yf02CumDg4wpfUsk/BPexxuQBfsEsI4hI=,tag:Abtc5a/BdpwBa3jkcSF7Kg==,type:str]
                passwordKey: ENC[AES256_GCM,data:P6BnxbPXm/W3FUyieXk=,iv:O4LdNMfc8LSMlXh3h3LCZM25FyscokRRk8dClDHYgTc=,tag:RJhRqBoLPClFnU9krXHEVQ==,type:str]
            env:
                GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:TVcl5lFifh8Z8IrpjjmBmRKH6dPfOQJi0nmaqpE13uEvh+p4jRWsBw==,iv:C0YsWETRXSlxA/r2FL02EmzWydTDpeMZwV/GFwoNDWA=,tag:upZ2OMe6F3cboJb/27uvMA==,type:str]
                GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:FJgIqPmt0ka7uY5p0Cq43Vgh+Gz49m/Y8OKTIKE4wBzARyiJ4XkoCOZ/TqZVbwtHMOs65gj33LY9oVTxn7NoqO/ct++t04RaMvs3WQR++Kl8rosyZrwXUrzoEWHZXHFVic8nk5Xd8GEFURTcevyaITsUpri/KDmAnzmJLUgYBUY=,iv:Qi+1jm9XrvcwAvP2LpLUPn07LPEnxmz/mJDZ+fHRWfs=,tag:9xqgoze141WJHX5oUDt5vA==,type:str]
            grafana.ini:
                server:
                    root_url: ENC[AES256_GCM,data:v6i30r5SHypREbTbLBDh7csKkor77oG9/vPCf4x+oiXsTw==,iv:DM6RSQfVK6I5E2r/C4B7+oZ0vj50nME9f0M7HkGc/ok=,tag:YMtAeUgec3QLtavABnrPKQ==,type:str]
                auth.generic_oauth:
                    enabled: ENC[AES256_GCM,data:hxhBpQ==,iv:gvj4VEsRtKz8L3t4ZxnpzDcB9ngmwSTkscUw2aqsggc=,tag:YUU53GgoUGrY0Y7X81mHUA==,type:bool]
                    name: ENC[AES256_GCM,data:/NHzXD+1RwjL,iv:B1TBTvTDYgrZx+1QS7EsoEMkURq806P7b7WcWHDrLAY=,tag:I4EbOQmny28nrk55jgpiWA==,type:str]
                    allow_sign_up: ENC[AES256_GCM,data:Ul7tRw==,iv:OVTYnYicReAgH9x+KPBKwoRrf11F7th43/WgJEiwOtU=,tag:o4kfdrNutXU5kOKaAlvSYA==,type:bool]
                    client_id: ENC[AES256_GCM,data:f9WgV4UG3Mef45GFD/zayw2sxyg8nsrvVGFq5vxSq8q4SjWf62+N,iv:p2zXzAN6pD2z0uU4NFrpTwdUM5HfCp7PTs0iyp4mQ4A=,tag:BplDBrkhxNPewgZQGUHn5w==,type:str]
                    client_secret: ENC[AES256_GCM,data:hzZtbNaRkvEWtGktYc35hEp4bpXd8gGusLu2SFrC883JjQR+k3mwXZLUWg==,iv:KWry+dv0jBuIp06uCppWbxgL1VfghG3ps5vPS3j8tKg=,tag:9U+iQhF4bTXOtdBn4JiTsA==,type:str]
                    scopes: ENC[AES256_GCM,data:I/d6uAJ4HXhe9bN9pxDqVpGuIG0=,iv:6QqKWIyC65EfQ9R4nSLkpqRys7XrCyVWGE2Uwl8PeTs=,tag:5T3ETSIJdMy7LoUi+e5zcQ==,type:str]
                    auth_url: ENC[AES256_GCM,data:yA0gS19KLLSjgQV5xeuJ90aCRbpV79vJuXm3xeMQHRk8jYIBI8eItqqLYnW1FSLYmruzWRShg6YhScXq,iv:yrNF39/bHt/4av2UrDi1tywpGBCtZ6rZ1tS0k/eIr0I=,tag:qHwoLY/wOBDilvZ4TOyWPw==,type:str]
                    token_url: ENC[AES256_GCM,data:jM34Ih0UQRDvXre5MO/8fdL+JGAF1kxIhxGTCkyVyXqAXuJi41RCEN5eezNNsd9vgxY67yQmzUU=,iv:SbrTP9Ws4P/QYrJdzp2bVNAsyYOt1diBs/BZam0MfMc=,tag:VTqDPsX/B6wvSFfTh+4AXg==,type:str]
                    api_url: ENC[AES256_GCM,data:SuyZ2Bn0AshGsOPLr0uwTI9QYg99ypmStqjwAViUQ+no8C7Q8c+egZmtgq5KFnkMxzGf2opS7rKXMeQ=,iv:voUpgFiXarQG/SmNOdZ2Bj3io+oWOQFD4ycvVBHqYiU=,tag:fnlyEqU2hzdfTRcrDIvJUg==,type:str]
                    role_attribute_path: ENC[AES256_GCM,data:OnLPaTRHcLiqcwwRj2UkgtiJosdcoup6aqSQgQKr5fmWbw55hUYKmippNlWEqDqX+K2667w2YI1pBEA=,iv:OaHsMhMG3BOrNEOWbYUuuCOuu8SqC3pySg7Boo0zVAM=,tag:pd/MnMcP3glA27m40v9GYA==,type:str]
            additionalDataSources:
                - name: ENC[AES256_GCM,data:I4F9Fw==,iv:zc7F/u268a4n9KHD2E2u/E7z2TPn3c+D0A89RmC8f/E=,tag:kaI6gli1z2dRNAeO5OuaFA==,type:str]
                  type: ENC[AES256_GCM,data:Nm1Z2g==,iv:wakjWZxYkgjGT3qpY3vOpzwXbIKRUTkVNT5JwTxNsB0=,tag:FmbvdnS9kOjgCjFkMR3VrQ==,type:str]
                  url: ENC[AES256_GCM,data:SWecocvnwjfWs4/K/DAFuh4KGml5PLqGno6krgM7Z5ucchbAUHzunt1nu3Oe,iv:aN4tqkler9qF0s/hjUAGQqICUeWfOtmZZfWs77wqnlE=,tag:YHb0DTegr6lt4YqoKAl17w==,type:str]
                  access: ENC[AES256_GCM,data:99VXxMc=,iv:gK3luNvCFn1bRLIWKTX7EJ36GCgB1ZezDNkZsaAnzp4=,tag:ZYw2o2IOWjoX+iLcX07eRw==,type:str]
                  isDefault: ENC[AES256_GCM,data:Krx2+9o=,iv:Z7PI49bIvdAJU/yRR3mW830vi7PM/zpR6yWnGDGhPr4=,tag:oSJ34yHwm+XZZX5JJuNR9w==,type:bool]
                - name: ENC[AES256_GCM,data:Ek2ucrQ=,iv:HFzkT+SUpMAlhfEjwPlYG0diQ9T8UVgKCtNbeQNTCM8=,tag:lIC/vgkLGgRhendPVzhmLw==,type:str]
                  type: ENC[AES256_GCM,data:pWxVYOU=,iv:xjzXSU96+H5Dzs7j7vSUdl+IvDbEkIc3obcNdWmkCAI=,tag:9t9/InZYhz74jcZE0Lc/EQ==,type:str]
                  url: ENC[AES256_GCM,data:/DZXDtlkujt+V5o9W+cEoY2DeFrfwPJWovcARO8YDZ7T9wjuz1MgWIg9J4IXAQ==,iv:R2rkmmQzJjnwSO08SrAqgwFxYCHC/2K2REfzVyvW5YQ=,tag:ntrjL0a1MtVZvXk0v/1QiQ==,type:str]
                  access: ENC[AES256_GCM,data:vyBX+KI=,iv:uULUXkv16X+JFERKLlezoMl1ZZyw2X8fv6r2n9iaVtM=,tag:2KGaeGa5m6/5+IIcpn8alw==,type:str]
                  isDefault: ENC[AES256_GCM,data:5s1knbM=,iv:dUtXJxQWFooLONoWudhGSTSpnXndunBN/YpY4jc5h98=,tag:oWGpjdec6SnuvW/Mem1iKg==,type:bool]
                  jsonData:
                    tracesToLogsV2:
                        datasourceUid: ENC[AES256_GCM,data:jZcqKQ==,iv:RIxBZXLpz9BdIeRfNlnWlXVIlNQDYgiF/8K00noegiE=,tag:8YLioH3N/yzxv4cf9Cbieg==,type:str]
                    lokiSearch:
                        datasourceUid: ENC[AES256_GCM,data:QFoGXA==,iv:j9e2ohe1n/CnEPW9xP92B1ueaBtXMNtFZzunsM+0awk=,tag:tuYQs8FqmsROh23LFQ+qvA==,type:str]
        prometheus:
            prometheusSpec:
                retention: ENC[AES256_GCM,data:+JJD,iv:sivouyUQKBhUaXeY3+wPAduOwmJuK7ZsEANjD+7f39U=,tag:/gRNMRqlOKhrc5mXrgTEWg==,type:str]
                storageSpec:
                    volumeClaimTemplate:
                        spec:
                            storageClassName: ENC[AES256_GCM,data:XVr7qVxIUmsMJQ==,iv:Xia6hq89lEg88zHOYB0Jne82BY8sV9Ywo7xhiIhmgqc=,tag:SFUUDbRYeqSm/PgsGhvX5g==,type:str]
                            accessModes:
                                - ENC[AES256_GCM,data:P80LZN5R+gt5gjdYlg==,iv:PfjzUiPZhOZruJMCDl9YYxJ/snakeSbgtmjAB2sXX44=,tag:90VOJm7pKXm+Qm3Z2N9+gw==,type:str]
                            resources:
                                requests:
                                    storage: ENC[AES256_GCM,data:ILyfCw==,iv:yzrPQdLz4bVc6qvc9QKjeE50/SEl1ANOY+fG0hnwfhA=,tag:+/Udmhjx+dA+/jvL3yo3PQ==,type:str]
        alertmanager:
            alertmanagerSpec:
                storage:
                    volumeClaimTemplate:
                        spec:
                            storageClassName: ENC[AES256_GCM,data:yv/zBz9tLKtwYw==,iv:Dh+tGqFUQ84T42iVFoa7rK+DBk4eHyMZ0Z05lAa//Eo=,tag:gwUBmjxHGZvPBDlCTYtV/g==,type:str]
                            accessModes:
                                - ENC[AES256_GCM,data:ksbY8S+MgMohx9YNqw==,iv:a/fME8Zq0ZSoqAO4ItMVy9hqs9s6BUGUBReJhPbp/5E=,tag:lKEpWweKRk+GTv63gEiN3Q==,type:str]
                            resources:
                                requests:
                                    storage: ENC[AES256_GCM,data:xK9p,iv:Twl5zxAwx2fOkztGw+flEd+JUzU7CjGwf9t3cpjGSNY=,tag:vkd6ptSp6hPo8RUH8yMPhQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Z0FFaGo2bTAzNWxjMG51
            T1N5WTNmSDMwZCtFMUFyQ0VEV1BXR0p0Y1ZzCjY4blRGcUtzdHFQcExyQ0JTcVpl
            OHQwSW1mMzF2amlGRFM0NUQwMXhXeDAKLS0tIHUzWDVDekpobXBXejkxY0Y5WEZ5
            MDI5aEtjM1JYVlVlVGsvNEFpK3FHUlkK4dELpo8Aae6qJ2pJJGIt34yLlS59f/sd
            l6WzaBEXnLjr8qFhBHGa9Y3IDq4+bWKvZz9i2+57335PsA+9fs9Ajg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sl4vva0g5zsk5mp9dqqwh34t7vtjd5m9dfqdpwl9ete638939q3sckw036
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFOHZGTWZ4VkFzOU1WeXJs
            K3dpR2hYZ1A2YmNNanBNSkJQbXlmVFhVa0FVClJNUUxmUTNRcWNrYUdQVnJPdmtI
            NzBFMldhOWFDa0htV2pYeU4rVEo5a1EKLS0tIFBmVStZRGkzL1U0OWs1Q0hxenVo
            OWhtRzdSR2ZidFVuZC9HQjJkd0RheW8KHrWH0BU6hQy+nJdAYehMUchQROHrCoUx
            MDQiOKYHOOwVv+BLwLnApcTK2FVx+wDDnKJ+VIsz4oOQUuIDw5B0iw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fk5nsur35v85fk8kr62kk768zhw78lq8hwa3efy9lesf56dtz9usafq3yx
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVc3RGWXdHSlFSMWtyOHJW
            TzlQTXRPYnYrQ1RhOGgzQ200eUhhajViNUEwCnFjQjNKWS9vYmxzTkhMRy9vdFlv
            OUp6akVPYXdmdDJrREdsb3NMYjRUbUUKLS0tIDJVTm5JOEFxV0RNZ1VJY2FtdGxH
            b3lQY0dkMno2RWtiKzZYVDhEYnhXWEUKjIXtNfnRwI6yJxSfk95S+jnO/M4r0Ak7
            vZUQRWP9B1yhlt4+fzbC7Ccb+ceLScVpejE+37l8rXwC8YNiffIV2w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age132hqe27z8z6t79uzsaxh6yfn2vnshvc0n0dmad53fss67tvhxcrsxuk5sa
    lastmodified: "2026-10-06T15:47:04Z"
    mac: ENC[AES256_GCM,data:OFWKjEqEDBLxkMcKBQBQI4Zv7DwvJU4lyLINoTCBOxQwk3bgFKdt6ArcxLf/zLPJIlfCd8gDm8DSYstXSB4SgmvXjQIZtplmesEKyBaBIMmerMZZgXCM8/V+rtPKfb+VYYQPuwesvNUheYBFipDUfgabpGOwJvjvWX0TIcP3OL8=,iv:uVOSBmSu75nqmbkRlcam5WuH9CE/f9RvgLCVCaQehn8=,tag:5ZdB7zuWb15VvUC/TVsYgw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
