apiVersion: v1
kind: Service
metadata:
  name: loki-tailscale
  namespace: monitoring
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "loki"
spec:
  selector:
    app: loki-proxy
  ports:
    - port: 3100
      targetPort: 3100
  type: LoadBalancer
  loadBalancerClass: tailscale
